sudo: required
services:
    - docker

before_install:
    - docker build -t roberbnd/docker-kubernetes -f Dockerfile.dev

script:
    - docker run roberbnd/docker-kubernetes npm run test -- --coverage